# Generated by Django 4.0.3 on 2022-03-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_supers_super'),
        ('supers_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperTypes',
            new_name='SuperType',
        ),
    ]
