# Generated by Django 4.0.3 on 2022-03-20 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_supers_super'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='supers_types_id',
            new_name='type',
        ),
    ]
